services:
  devportfolio:
    image: devportfolio:dev
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    environment:
      NODE_ENV: development
    ports:
      - 5173:5173
